system: Eres un asistente de IA con mucho conocimiento que ayuda al usuario con su tarea.

introduction: |
  Tu tarea es evaluar la relevancia de una respuesta dada a una consulta específica. Esta evaluación debe realizarse de manera metódica respondiendo dos preguntasave:

principles: |
  1. Subject Matter Relevance: ¿La respuesta proporcionada coincide con precisión con el tema de la consulta del usuario? Esta pregunta tiene como objetivo determinar si la respuesta está directamete relacionada con el tema o asunto principal presentado en la consulta.
  2. Focus and Perspective Addressing: ¿La respuesta proporcionada aborda efectivamente el enfoque o la perspectiva sobre el tema, tal como se indica en la consulta del suario? Esta pregunta busca evaluar si la respuesta no solo coincide con el tema, sino que también se ajusta a la intención o  preocupación específica planteada por usuario.

  Para cada pregunta, asigna 1 punto si la respuesta cumple con el criterio, y 0 puntos si no lo cumple. Después de evaluar cada pegunta, proporciona comentarios detallados explicando tu razonamiento detrás de los puntos otorgado.

  Concluye tu evaluación con un resultado final que debe estrictamente ir en el siguiente formato: 'Total Score: X'. La puntuación total debe representar la suma de lospuntos asignados por cada pregunta, con una puntuación máxima posible de 2 puntos.
  Evalúa la respuesta solo en función de los criterios anteriores, no crees nuevas preguntas.

examples: |
  Example 1:
  [Start of Question]
  ¿Cuál es el impacto del calentamiento global en osos polares?
  [End of Question]

  [Start of Response]
  El calentamiento global provoca el derretimiento de los casquetes polares, reduciendo el hábitat de los osos polares e impactando negativamente sus terrenos de caza.
  [End of Response]

  [Start of Feedback]
  - Subject Matter Relevance Score: 1 (La respuesta está directamente relacionada con el impacto del calentamiento global en los osos polares.
  - Alignment with Query's Focus Score: 1 (La respuesta aborda específicamente cómo el calentamiento global afecta el hábitat de los osos polares y sus terrenos caza.)
  [End of Feedback]

  [Start of Score]
  2
  [End of Score]

  Example 2:
  [Start of Question]
  ¿Cómo funciona la fotosíntesis?
  [End of Question]

  [End of Response]
  Las plantas necesitan agua y luz para crecer.
  [End of Response]

  [Start of Feedback]
  - Subject Matter Relevance Score: 0 (La respuesta está relacionada con el crecimiento de las plantas, pero no aborda específicamee la respuesta del usuario)
  - Alignment with Query's Focus Score: 0 (La respuesta no detalla el proceso de fotosíntesis, omitiendo el enfoque específico de la conlta )
  [End of Feedback]

  [Start of Score]
  0
  [End of Score]


  Example 3:
  [Start of Question]
  ¿Cuáles son los beneficios de los coches eléctricos?
  [End of Question]

  [Start of Response]
  Los coches eléctricos reducen la dependencia de los combustibles fósiles y disminuyen las emisiones de gases de efecto invernadero.
  [End of Response]

  [Start of Feedback]
  - Subject Matter Relevance Score: 1 (La respuesta coincide con el tema de la consulta sobre los beneficios de los vehículos eléctrico )
  - Alignment with Query's Focus Score: 1 (La respuesta aborda eficazmente los beneficios ambientales de los vehículos eléctricos, alineándose con el enfoque sulta )
  [End of Feedback]

  [Start of Score]
  2
  [End of Score]

generation: |
  Comienza tu respuesta proporcionando los comentarios seguidos de la puntuación. Debes ser lo mas objetivo posible.
  [Start of Question]
  {question}
  [End of Question]

  [Start of Response]
  {response}
  [End of Response]

  * Devuelve el feedback ente los tags [Start of Feedback] y [End of Feedback].
  * Devuelve la puntuación final ente los tags [Start of Score] y [End of Score].
start_tags: ["[Start of Feedback]", "[Start of Score]"]
end_tags: ["[End of Feedback]", "[End of Score]"]
