system: Eres un asistente de IA de gran conocimiento que ayuda fielmente al usuario con su tarea.

introduction: Desarrolla una serie de pares de pregunta y respuesta educativos a partir de un capitulo de un libro de texto de {domain}.

principles: | 
  Las preguntas deben:

  * Ser autónomas, no requiriendo referencias a tablas, figuras o secciones específicas del texto para su comprensión.
  * Estar enfocadas en enseñar y reforzar el conocimiento clave y los conceptos presentados en el capítulo.
  * Evitar secciones con contenido educativo mínimo, como páginas de índice o prefacios. En tales casos, responde con [UNANSWERABLE].
  * Ser directamente relevantes para el dominio del libro de texto. Por ejemplo, en un libro de texto de ciencias, las preguntas deben girar en torno a términos cient­íficos, definiciones y aplicaciones prácticas, mientras que en un libro de texto de derecho, deben abordar principios legales, jurisprudencia y precedentes.
  * Estar formuladas para permitir respuestas independientes, evitando referencias directas a teoremas especificos o secciones del texto. Por ejemplo, en lugar de preguntar '¿Bajo que condiciones el punto fijo de una funcion es unico segun el Teorema 3.1.5?', pregunta '¿Cómo contribuye el metodo de Iteración de Puntos Fijos a entender la unicidad de una funcion?'
  * Cubrir una variedad de niveles de dificultad para acomodar a una audiencia estudiantil diversa, desde la comprensión básica hasta la avanzada.
  * Incluir una variedad de tipos de preguntas, como opción múltiple para recordar información básica, respuestas cortas para comprensión más profunda, y preguntas de ensayo o resolución de problemas para evaluar habilidades de aplicación y análisis.
  * Alinear estrechamente con los objetivos de aprendizaje del libro de texto o del capitulo especifico, asegurando que las preguntas prueben que los conceptos y habilidades fundamentales que el capitulo pretende impartir.
  Sigue estrictamente este formato para cada par de pregunta y respuesta que generes al responder.
  [QUESTION]
  <Insertar pregunta>
  [ANSWER]
  <Insertar respuesta>
  [END] 
   Cada par de pregunta y respuesta debe se autonoma como una mini-leccion, encapsulando un concepto o idea clave de manera accesible e informativa sin que el lector necesite nuevamente consultar el texto

examples: |
  Algunos ejemplos:

  [Document]
  {icl_document}

  [QUESTION]
  {icl_query_1}
  [ANSWER]
  {icl_response_1}
  [END]

  [QUESTION]
  {icl_query_2}
  [ANSWER]
  {icl_response_2}
  [END]

  [QUESTION]
  {icl_query_3}
  [ANSWER]
  {icl_response_3}
  [END]

generation: |
  Aqui esta el documento:

  [DOCUMENT]
  {document_outline}
  {document}
