system: Eres un asistente, experto en generar peguntas y respuestas basadas en las guidelines dadas.
introduction: Crea una serie de preguntas de opciones múltiples siguiendo las guidelines proporcionadas a continuación.
principles: | 
  Guidelines para generar:
  * Crea preguntas de opciones múltiples basadas en los datos presentados en los documentos proporcionados.
  * Cada pregunta debe ir junto a una respuesta correcte que muestre correctamente los datos.
  * Debes asegurarte de que la pregunta y respuesta estan basadas en el documento proporcionado.
  * Devuelve la pregunta entre los tags [Start of Question] y [End of Question].
  * Devuelve la respuesta dentro de los tags [Start of Answer] y [End of Answer].
  
  Sigue esta estructura para cada ejemplo:
  [Start of Document]
  El punto de ebullición del agua es la temperatura a la que cambia de liquido a gas. Esto ocurre a 100 grados Celsius bajo condiciones de presión atmósferica standar.
  [End of Document]

  [Start of Question]
  ¿Qué representa el punto de ebullición del agua?

  A) Solidificación
  B) Evaporación
  C) Condensación
  D) Congelación 

  [End of Question]

  [Start of Answer]
  B) Evaporación
  [End of Answer]

examples: |
  
  Example 1:
  [Start of Document]
  La fotosíntesis es un proceso utilizado por las plantas, algas y ciertas bacterias para convertir la energia lumínica en energía química. Este proceso involucra absorción de luz por la clorofila, la conversión de dióxido de carbono inorganico (CO2) en compuestos orgánicos, y la liberación de oxígeno como subproducto. La ecuación general de la fotosíntesis se puede representar como.
  6CO2 + 6H2O + light energy → C6H12O6 + 6O2.  
  [End of Document]

  [Start of Question]
  ¿Cuál es la funcion principal de la fotosíntesis en las plantas?

  A) Producir dióxido de carbono
  B) Convertir la energía lumínica en energía química
  C) Absorber oxígeno de la atmósfera
  D) Liberar dióxido de carbono al medio ambiente
 
  [Start of Answer]
   B) Convertir la energía lumínica en energía química
  [End of Answer]

  Example 2:
  [Start of Document]
  El comercio electrónico abreviado como e-commerce se refiere a la compra y venta de bienes y servecios por internet. Abarca muchas transacciones, incluyendo B2B (empresa a empresa), B2C (empresa a consumidor) y C2C (consumidor a consumidor). Las plataformas de e-commerce pueden ser puramente digitales o combinar operaciones online o en tienda física.
  [End of Document]

  [Start of Question]
  ¿El comercio electrónico involucra principalmente qué tipo de transacciones?
 
  A) Digital
  B) Local
  C) Manual
  D) Verbal
  [End of Question]

  [Start of Answer]
   A) Digital
  [End of Answer]

generation: |
  Sigue las guidelines y estructura de arriba para crear preguntas de eleccion múltiple, con la respuesta correcta, basadas en el documento proporcionado.
  * Devuelve la pregunta entre los tags [Start of Question] y [End of Question].
  * Devuelve la respuesta entre los tags [Start of Answer] y [End of Answer].

  Here is the document:
  [Start of Document]
  {document}
  [End of Document]

start_tags: ["[Start of Question]", "[Start of Answer]"]
end_tags: ["[End of Question]", "[End of Answer]"]
