system: Eres un asistente, experto en generar peguntas y respuestas basadas en las guidelines dadas.
introduction: Crea una serie de preguntas de opciones multiples siguiendo las guidelines proporcionadas a continuacion.
principles: | 
  Guidelines para generar:
  * Crea preguntas de opciones multiples basadas en los datos presentados en los documentos proporcionados.
  * Cada pregunta debe ir junto a una respuesta correcte que muestre correctamente los datos.
  * Debes asegurarte de que la pregunta y respuesta estan basadas en el documento proporcionado.
  * Devuelve la pregunta entre los tags [Start of Question] y [End of Question].
  * Devuelve la respuesta dentro de los tags [Start of Answer] y [End of Answer].
  
  Sigue esta estructura para cada ejemplo:
  [Start of Document]
  El punto de ebullicion del agua es la temperatura a la que cambia de liquido a gas. Esto ocurre a 100 grados Celsius bajo condiciones de presion atmosferica standar.
  [End of Document]

  [Start of Question]
  Que representa el punto de ebullicion del agua?

  A) Solidificacion
  B) Evaporacion
  C) Condensacion
  D) Congelacion 

  [End of Question]

  [Start of Answer]
  B) Evaporacion
  [End of Answer]

examples: |
  
  Example 1:
  [Start of Document]
  La fotosintesis es un proceso utilizado por las plantas, algas y ciertas bacterias para convertir la energia luminica en energia quimica. Este proceso involucra absorcion de luz por la clorofila, la conversion de dioxido de carbono inorganico (CO2) en compuestos organicos, y la liberacion de oxigeno como subproducto. La ecuacion general de la fotosintesis se puede representar como.   
  [End of Document]

  [Start of Question]
  ¿Cual es la funcion principal de la fotosintesis n las plantas?

  A) Producir dioxido de carbono
  B) Convertir la energia luminica en energia quimica
  C) Absorber oxigeno de la atmosfera
  D) Liberar dioxido de carbono al medio ambiente
 
  [Start of Answer]
   B) Convertir la energia luminica en energia quimica
  [End of Answer]

  Example 2:
  [Start of Document]
  El comercio electronico abreviado como e-commerce se refiere a la compra y venta de bienes y servecios por internet. Abarca muchas transacciones, incluyendo B2B (empresa a empresa), B2C (empresa a consumidor) y C2C (consumidor a consumidor). Las plataformas de e-commerce pueden ser puramente digitales o combinar operaciones online o en tienda fisica
  [End of Document]

  [Start of Question]
  El comercio electronico involucra principalmente que tipo de transacciones?
 
  A) Digital
  B) Local
  C) Manual
  D) Verbal
  [End of Question]

  [Start of Answer]
   A) Digital
  [End of Answer]

generation: |
  Sigue las guidelines y estructura de arriba para crear preguntas de eleccion multiple, con la respuesta correcta, basadas en el documento proporcionado.
  * Devuelve la pregunta entre los tags [Start of Question] y [End of Question].
  * Devuelve la respuesta entre los tags [Start of Answer] y [End of Answer].

  Here is the document:
  [Start of Document]
  {document}
  [End of Document]

start_tags: ["[Start of Question]", "[Start of Answer]"]
end_tags: ["[End of Question]", "[End of Answer]"]
