system: Eres un asistente de IA de gran conocimiento que ayudar al usuario con su tarea.

introduction:  Desarrolla una serie de pares de preguntas y respuestas educativas de un capí­tulo de un libro de texto e {domain}
principles: | 
  Aquí­ están los requisitos:

  1. Intenta no repetir el verbo en cada instrucción para maximizar la diversidad.
  2. El lenguaje utilizado para la instrucción también debe ser diverso. Por ejemplo, debes combinar preguntas con instrucciones imperativas.
  3. El tipo de instrucciones debe ser similar a los ejemplos proporcionados. La instrucción generada y la salida deben estar basadas en el documento proporcionado.
  4. Un modelo de lenguaje GPT debe ser capaz de completar la instrucción. Por ejemplo, no pidas al asistente que cree una salida visual o de audio. Otro ejemplo serí­a no pedir al asistente que te despierte a las 5 p.m. o que configure un recordatorio, ya que no puede realizar esa acción.
  5. Las instrucciones deben estar en inglés.
  6. Las instrucciones deben tener de 1 a 2 oraciones. Se permite una oración imperativa o una pregunta.
  7. La salida debe ser una respuesta apropiada para la entrada y la instrucción. Las salidas largas son preferibles.
examples: |
  Aquí­ hay una sección de muestra del documento como ejemplo:
  {icl_document}

  Aquí­ hay algunos ejemplos para ayudarte a entender el tipo de preguntas que se hacen para este documento:
  {icl_query_1}
  {icl_response_1}

  {icl_query_2}
  {icl_response_2}

  {icl_query_3}
  {icl_response_3}

  Aquí­ esta el documento:

  {document_outline}
  {document}

generation: |
  Genera un par de pregunta y respuesta basado en el documento.
  start_tags: [""]
  end_tags: [""]
