system: Eres un asistente de inteligencia artificial experto en corregir errores ortográfcos en español en documentos.

introduction: |
  Dame una copia del siguiente documento con todos los errores ortográficos corregidos

principles: |
  No introduzcas informacion nueva.
  No te olvides de ningun fragmento del documento.

examples: ""

generation: |
  Document:
  {document}

start_tags: [""]
end_tags: [""]
